# Generated by Django 3.2.5 on 2021-09-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nguoidung',
            options={},
        ),
        migrations.AlterModelTable(
            name='bangcap',
            table='bang_cap',
        ),
        migrations.AlterModelTable(
            name='chucdanh',
            table='chuc_danh',
        ),
        migrations.AlterModelTable(
            name='danhgianhatuyendung',
            table='danh_gia_nha_tuyen_dung',
        ),
        migrations.AlterModelTable(
            name='kinhnghiem',
            table='kinh_nghiem',
        ),
        migrations.AlterModelTable(
            name='kynang',
            table='ky_nang',
        ),
        migrations.AlterModelTable(
            name='nganhnghe',
            table='nganh_nghe',
        ),
        migrations.AlterModelTable(
            name='nguoidung',
            table='nguoi_dung',
        ),
        migrations.AlterModelTable(
            name='nhatuyendung',
            table='nha_tuyen_dung',
        ),
        migrations.AlterModelTable(
            name='phucloi',
            table='phuc_loi',
        ),
        migrations.AlterModelTable(
            name='quanly',
            table='quan_ly',
        ),
        migrations.AlterModelTable(
            name='ungtuyen',
            table='ung_tuyen',
        ),
        migrations.AlterModelTable(
            name='ungvien',
            table='ung_vien',
        ),
        migrations.AlterModelTable(
            name='ungvienbangcap',
            table='ung_vien_bang_cap',
        ),
        migrations.AlterModelTable(
            name='ungvienkinhnghiem',
            table='ung_vien_kinh_nghiem',
        ),
        migrations.AlterModelTable(
            name='ungvienkynang',
            table='ung_vien_ky_nang',
        ),
        migrations.AlterModelTable(
            name='ungviennganhnghe',
            table='ung_vien_nganh_nghe',
        ),
        migrations.AlterModelTable(
            name='vieclam',
            table='viec_lam',
        ),
    ]
